# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

en:
  languageCode: en-us
  contentDir: content/en
  title: Xin Chen
  params:
    marketing:
      seo:
        description: >-
          Dr. Xin Chen is a Postdoctoral Researcher at the Key Laboratory of Data Engineering and Knowledge Engineering, Renmin University of China. His research focuses on designing efficient query and computational methods to enhance visual analytics of large-scale data. He earned his Bachelor of Engineering in Software Engineering (2018) and Ph.D. in Computer Science and Technology (2024) from Shandong University.
    locale:
      address_format: en
      date_format: 01-02-2006

zh:
  languageCode: zh-Hans
  contentDir: content/zh
  title: 陈昕
  params:
    marketing:
      seo:
        description: >-
          陈昕，博士，现任中国人民大学数据工程与知识工程教育部重点实验室博士后研究员。他的研究方向为设计高效的查询和计算方法，以提升对大规模数据的可视分析能力。他于2018年获山东大学软件工程工学学士学位，2024年获山东大学计算机科学与技术博士学位。
    locale:
      address_format: cn
      date_format: '2006-01-02'